#Create DB
create or replace database abhi;

#Create Schema
create or replace schema Abhishek;
SHOW SCHMA;

#CREATE EXTERNAL STAGE(S3 BUCKET), TO USE THIS COMMAND SET IAM ROLE TO ACCESS S3 ON AWS
CREATE OR REPLAE STAGE_INGESTION.S3_STAGE
  URL = 'S3 PATH'
  CREDENTIALS = (
    AWS_KEY_ID = 'ID'
    AWS_SECRET_KEY = 'KEY'
   );
  
#TO SHOW ALL THE FILES IN BUCKET
LIST @INGESTION.S3_STAGE;

#ANY FILE FORMAT CAN BE UPLOADED TO SNOWFLAKE LIKE AVRO,PARQUET,JSON,CSV,XML ETC UNDER DATABASE -> FILE FORMAT FOR UI TO LOAD FILES

#CREATE TABLE
CREATE OR REPLACE TABLE CURATIONS.EVENTS(
  ID STRING,
  ASSETS STRING,
  VALUE INT(18,9),
  CREATED INT,
  ATTRIBUTES VARIANT --FOR UNSTRUCTURED DATA
);

DESC TABLE CURATIONS.EVENTS;

#INSERT DATA FROM S3 TO TABLE
COPY INTO CURATION.EVENTS 
  FROM @INGESTION.S3_STAGE/EVENTS/ 
  FILE_FORMAT = (FORMATE_NAME = 'INGESTION.CSV_FORMAT' );
  
#LOAD DATA TAKES TIME BUT IF YOU WANT TO SCALE IT UP FOR FASTER LOADING
ALTER WAREHOUSE NAME_OF_WH SET WH_SIZE = 'XXLARGE';

SELECT SELECT LAG(VALUE) OVER (PARTITION BY ID ORDER BY EVENTS) AS PREV_VALUE FROM CURATIONS.EVENTS;

#ENABLE THE CACHE
ALTER SESSION SET USE_CACHED_RESULT = TRUE;

#TO RECOVER DELETED DATA WHICH HAPPENED AT 5 MINS OF TIMEFRAME(THIS WILL WORK FOR ACCIDENTAL DELETED DATA AND OFFSET CAN BE CHANGED BASED ON TIME)
SELECT COUNT(ID) AS NUM_ASSETS 
FROM CURATION.ASSETS AT (OFFSET => -60*5) 
WHERE TYPE = 'CAR';

#FROM HISTORY QUERY ID CAN BE FINDABLE
INSERT INTO CURATIONS.ASSETS 
SELECT * FROM CURATION.ASSETS 
BEFORE (STATEMENT => 'QUERY ID FROM WHERE DATA GOT DELETED') 
WHERE TYPE = 'CAR';
